/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.wpi.first.wpilibj.templates.commands;



/**
 *
 * @author Justin
 */
public class MecDrive extends CommandBase {
    
   public final double DEADBAND = .4;
    private final double SENSITIVITY = .6;
    public double xValue;
    public double yValue;
    public double twist;
    public MecDrive() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(driveTrain);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    yValue = SENSITIVITY*fixDeadBand(oi.getJoystick1().getY(), DEADBAND); //reverses joystick y
    xValue = -SENSITIVITY*fixDeadBand(oi.getJoystick1().getX(), DEADBAND);
    twist = -SENSITIVITY*fixDeadBand(oi.getJoystick1().getTwist(), DEADBAND*2); //double deadband
    
    double front_left = yValue + twist + xValue;
    double front_right = yValue - twist - xValue;
    double back_left = yValue + twist - xValue;
    double back_right = yValue - twist + xValue;
    
    double max = Math.abs(front_left);
    if (Math.abs(front_right)>max) {
        max = Math.abs(front_right);
    }
    if (Math.abs(back_left)>max){
        max=Math.abs(back_left);
    }
    if (Math.abs(back_right)>max) {
        max=Math.abs(back_right);
    }
    if (max>1){
      front_left/=max; front_right/=max; back_left/=max; back_right/=max;

    }

    driveTrain.mecanumDrive(front_left, front_right, back_left, back_right);
    
    if(Math.abs(xValue + yValue + twist) > 0){
        System.out.println("X1: " + xValue + " Y: " + yValue + " T: " + twist);
        System.out.println("FL: "+ driveTrain.frontLeft.get() + " BL: " +
                driveTrain.backLeft.get() + " FR: " + driveTrain.frontRight.get() + " BR: " +
                driveTrain.backRight.get());
    }
 

//    Robot.oi.getJoystick1().getTwist());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
     }
    
    private double fixDeadBand(double speed, double deadBand) {
        return (Math.abs(speed) > deadBand ? speed : 0.0);
    }
}
