// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package edu.wpi.first.wpilibj.templates.subsystems;


import edu.wpi.first.wpilibj.Gyro;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Victor;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.templates.RobotMap;
import edu.wpi.first.wpilibj.templates.commands.MecanumDrive;

/**
 *
 */
public class DriveTrain extends Subsystem {
    public Victor backRight;// = RobotMap.driveTrainBackRight;
    public Victor frontRight;// = RobotMap.driveTrainFrontRight;
    public Victor backLeft;// = RobotMap.driveTrainBackLeft;
    public Victor frontLeft;// = RobotMap.driveTrainFrontLeft;
    public RobotDrive mecanumDrive;// = RobotMap.mecanumDrive;
    public Gyro gyro;
    
    public DriveTrain(){
        backRight = new Victor(RobotMap.RIGHT_MOTOR_BACK);
        frontRight = new Victor(RobotMap.RIGHT_MOTOR_FRONT);
        backLeft = new Victor(RobotMap.LEFT_MOTOR_BACK);
        frontLeft = new Victor(RobotMap.LEFT_MOTOR_FRONT);
        mecanumDrive = new RobotDrive(frontLeft, backLeft, frontRight, backRight);
        gyro = new Gyro(RobotMap.GYRO_PORT);
//        mecanumDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft,false);
//        mecanumDrive.setInvertedMotor(RobotDrive.MotorType.kFrontLeft,false);
//        mecanumDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight,true);
//        mecanumDrive.setInvertedMotor(RobotDrive.MotorType.kFrontRight,true);
    }
    
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
        setDefaultCommand(new MecanumDrive());
    }
    public void rightFrontMove(double speed){
        frontRight.set(speed);
    }
    
    public void rightBackMove(double speed){
        backRight.set(speed);
    }
        public void leftFrontMove(double speed){
        frontLeft.set(speed);
    }
            public void leftBackMove(double speed){
        backLeft.set(speed);
    }
    
}

