// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2854.Encoder;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Encoder pIDSubsystem1QuadratureEncoder1;
    public static SpeedController pIDSubsystem1SpeedController1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        pIDSubsystem1QuadratureEncoder1 = new Encoder(1, 1, 1, 2, false, EncodingType.k4X);
	LiveWindow.addSensor("PID Subsystem 1", "Quadrature Encoder 1", pIDSubsystem1QuadratureEncoder1);
        pIDSubsystem1QuadratureEncoder1.setDistancePerPulse(1.0);
        pIDSubsystem1QuadratureEncoder1.setPIDSourceParameter(PIDSourceParameter.kRate);
        pIDSubsystem1QuadratureEncoder1.start();
        pIDSubsystem1SpeedController1 = new Victor(1, 1);
	LiveWindow.addActuator("PID Subsystem 1", "Speed Controller 1", (Victor) pIDSubsystem1SpeedController1);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
